services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    depends_on: 
      - 'esv-server'
    command: 
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARE_TOKEN}
    restart: unless-stopped

  esv-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: esv-server
    #ports:
    #  - '8888:8888'
    #volumes:
    #  - ./tmp:/app/tmp
    restart: unless-stopped
